export const FILMS_DATA_GET_REQUEST = 'FILMS_DATA_GET_REQUEST';
export const FILMS_DATA_GET_SUCCESS = 'FILMS_DATA_GET_SUCCESS';
export const FILMS_DATA_GET_FAILURE = 'FILMS_DATA_GET_FAILURE';

export const PLACE_LOCATION_REQUEST = 'PLACE_LOCATION_REQUEST';
export const PLACE_LOCATION_SUCCESS = 'PLACE_LOCATION_SUCCESS';
export const PLACE_LOCATION_FAILURE = 'PLACE_LOCATION_FAILURE';

export const FILM_DETAILS_GET_REQUEST = 'FILM_DETAILS_GET_REQUEST';
export const FILM_DETAILS_GET_SUCCESS = 'FILM_DETAILS_GET_SUCCESS';
export const FILM_DETAILS_GET_FAILURE = 'FILM_DETAILS_GET_FAILURE';

export const CURRENT_LOADING_FILM_CHANGED = 'CURRENT_LOADING_FILM_CHANGED';
export const SEARCH_QUERY_UPDATE = 'SEARCH_QUERY_UPDATE';
